### PR TITLE
Merge Dev into Master

### PR DESCRIPTION
**Pull request by dannysmith**
I've opened this PR to track changes on dev that need merging into master for release.

### CODE REVIEW

**Comment by dannysmith** [comment]
It looks like you didn't get a chance to merge the new stuff from this afternoon into `dev`. Having looked over what's currently in dev branch, everything looks pretty good.

I have a few suggestions/points, though:
1. There seems to be a lot of logging in and out - is there any way we could be smarter about this so as to avoid logging out and then in again if unnecessary. I'm thinking we could get the execution time down a bit.
2. Line 15 of `profile.feature` and the associated step defs file has a typo.
3. We can maybe reduce execution time and make things a bit more resilient by using URLs more often.
4. There are still some hard-coded URLs dotted about the place.

Otherwise - good job 👏 . Look forward to seeing the 2-browser thing and messaging stuff merged in tomorrow.

### Logging in and Out

A good example of the logging in and out thing is this step def:

``` ruby
Given(/^I am on the profile page$/) do
  @system.login_page.visit
  @system.login_page.send_login_credentials(TestData.users[1][:email], TestData.users[1][:password])
  @system.login_page.check_for_channel('general')
  @system.profile_page.open_profile
end
```

Do we actually need to log out and then in here?

### Using URLs more

On a similar note, the `open_profile` method on the `ProfilePage` does a lot of clicking and waiting. I reckon we might be able to simplify it by hitting `https://#{base_url}/team/#{username}` and clicking the edit button. I suspect there are a few more places where some clever work with URLs will save some waits and clicks and such like. (This only makes sense if we're not actually **testing** the clicking of buttons etc.)

### Hard Coded URLs

There are still some hard-coded URLs dotted about the place.

screen shot 2016-10-18 at 21 54 01

/cc @johnmetcalfe @cjdpearce @alexmacaulay @AlfieThornton93

**Comment by dannysmith** [comment]
Looks good, chaps. cc/ @alexmacaulay @cjdpearce

**Comment by ghost** [comment]
Looking good overall! Although I found really tiny quirks.

**generic_page.rb**

```
class GenericPage
include RSpec::Matchers
include Selenium::WebDriver
@@wait = Selenium::WebDriver::Wait.new(timeout: 20000)
```

> Indentations.

**login_page.rb**

```
# class Selenium::WebDriver::HTMLElement
#   def when_present
#     wait.until { self.displayed? }
#     return self
#   end
# end
#
# el(:time_zone_expand_button).when_present.click
```

> Commented code. Will this still be used in the future? If so, perhaps add a commented out description at the top of this block.

**profile_page.rb**

```
  @@dictionary = {
    edit_profile_open: "#member_preview_scroller > div > div.member_action_bar > a:nth-child(1)",
    team_menu: "#team_menu",
    team_menu_profile: "#member_account_item > a",
    first_name: "#edit_member_profile_list > div.clearfix.display_flex.flex_wrap.position_relative > p > input",
    profile_save: "#fs_modal_footer > button.btn.left_margin.dialog_go.edit_member_profile_confirm_edit_btn.ladda-button > span.ladda-label",
    last_name: "#edit_member_profile_list > div:nth-child(3) > p > input",
    what_I_do: "#edit_member_profile_list > div:nth-child(4) > p > input",
    phone_number: "#edit_member_profile_list > div:nth-child(5) > p > input",
    skype: "#edit_member_profile_list > div:nth-child(6) > p > input"



  }
```

> Too many newline characters.

Also, are there any reasons for the `sleep` methods?

**Comment by ghost** [comment]
I've also got a recommendation for refactoring your `@@wait.until blocks`. As testers, you should collaboratively come up with a decision on this -- whether you want to go with it or not.

Create a new module called `WaitUntil` and save it as `wait_until.rb` in a separate folder called `modules`:

```
module WaitUntil
  def wait_until condition
    wait.until {condition}
  end
end
```

Instead of using a class variable for storing the wait default in the `GenericPage` class, use a method instead:

```
def wait
  Selenium::WebDriver::Wait.new(timeout: 20000)
end
```

And don't forget to include the `WaitUntil` module:

**env.rb**

```
...
# because you might have more than one module in the future
Dir['./features/support/modules/*.rb'].each{|file| require file}
...
```

**generic_page.rb**

```
class GenericPage
  ...
  include WaitUntil
  ...
end
```

From within a page class, you can then do the following:

```
def wait_for_something
  # invoke the wait_until method that was defined in the WaitUntil module
  # 1 == 1 is just a sample condition, you could obviously use el(:something).displayed?
  wait_until 1 == 1
end
```

So you then have:

`wait_until(condition)`

as opposed to:

**profile_page.rb**

```
def open_profile
  sleep 2
  @@wait.until do
    el(:team_menu).displayed?
  end
  el(:team_menu).click
  sleep 2
  @@wait.until do
    el(:team_menu_profile).displayed?
  end
  el(:team_menu_profile).click
  sleep 2
  @@wait.until do
    el(:edit_profile_open).displayed?
  end
  el(:edit_profile_open).click
  sleep 2
end
```

Which makes your code look more pragmatic.

And again, the `sleep` methods, is there a reason for them?

**Pull request closed without merging**
